#if !defined(AFX_MEMORY_H__2E67C5D8_04AA_4574_B006_083004C6C07B__INCLUDED_)
#define AFX_MEMORY_H__2E67C5D8_04AA_4574_B006_083004C6C07B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMemory wrapper class

class CMemory : public COleDispatchDriver
{
public:
	CMemory() {}		// Calls COleDispatchDriver default constructor
	CMemory(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMemory(const CMemory& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetChannelNO();
	void SetChannelNO(long nNewValue);
	CString GetChannelID();
	void SetID(LPCTSTR lpszNewValue);
	void GetReferenceColor(LPCTSTR ProbeIDVal, float* XVal, float* YVal, float* LvVal);
	void SetChannelID(LPCTSTR ChannelIDVal);
	void GetMemoryStatus(long ProbeNOVal, long* CalProbeSNOVal, long* RefProbeSNOVal, long* CalModeVal);
	long CheckCalData(long ProbeNOVal, LPCTSTR FileNameVal);
	void CopyToFile(long ProbeNOVal, LPCTSTR FileNameVal);
	void CopyFromFile(long ProbeNOVal, LPCTSTR FileNameVal);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MEMORY_H__2E67C5D8_04AA_4574_B006_083004C6C07B__INCLUDED_)
