// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "outputprobes.h"

// Dispatch interfaces referenced by this interface
#include "probe.h"


/////////////////////////////////////////////////////////////////////////////
// COutputProbes properties

/////////////////////////////////////////////////////////////////////////////
// COutputProbes operations

CProbe COutputProbes::GetItem(const VARIANT& ProbeIndexVal)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x0, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		&ProbeIndexVal);
	return CProbe(pDispatch);
}

long COutputProbes::GetCount()
{
	long result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void COutputProbes::Add(LPCTSTR ProbeIDVal)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 ProbeIDVal);
}

CProbe COutputProbes::GetItemOfNumber(long ProbeNumberVal)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		ProbeNumberVal);
	return CProbe(pDispatch);
}

void COutputProbes::AddAll()
{
	InvokeHelper(0x7, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

COutputProbes COutputProbes::Clone()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, NULL);
	return COutputProbes(pDispatch);
}

void COutputProbes::RemoveAll()
{
	InvokeHelper(0x9, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
