// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "probes.h"

// Dispatch interfaces referenced by this interface
#include "probe.h"


/////////////////////////////////////////////////////////////////////////////
// CProbes properties

/////////////////////////////////////////////////////////////////////////////
// CProbes operations

CProbe CProbes::GetItem(const VARIANT& IndexVal)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x0, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		&IndexVal);
	return CProbe(pDispatch);
}

long CProbes::GetCount()
{
	long result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

CProbe CProbes::GetItemOfNumber(long ProbeNumber)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		ProbeNumber);
	return CProbe(pDispatch);
}

void CProbes::SetProbeID(long ProbeNumberVal, LPCTSTR ProbeIDVal)
{
	static BYTE parms[] =
		VTS_I4 VTS_BSTR;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 ProbeNumberVal, ProbeIDVal);
}
