#if !defined(AFX_PROBES_H__93F8CADF_753C_4E39_9AD3_97D4C9ED5E35__INCLUDED_)
#define AFX_PROBES_H__93F8CADF_753C_4E39_9AD3_97D4C9ED5E35__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CProbe;

/////////////////////////////////////////////////////////////////////////////
// CProbes wrapper class

class CProbes : public COleDispatchDriver
{
public:
	CProbes() {}		// Calls COleDispatchDriver default constructor
	CProbes(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CProbes(const CProbes& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CProbe GetItem(const VARIANT& IndexVal);
	long GetCount();
	CProbe GetItemOfNumber(long ProbeNumber);
	void SetProbeID(long ProbeNumberVal, LPCTSTR ProbeIDVal);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PROBES_H__93F8CADF_753C_4E39_9AD3_97D4C9ED5E35__INCLUDED_)
